<a href="https://colab.research.google.com/github/penguinshunya/ml/blob/main/Dropout%E3%81%AF%E4%B8%80%E9%83%A8%E3%81%AE%E3%82%BB%E3%83%AB%E3%82%920%E3%81%AB%E3%81%99%E3%82%8B%E3%81%A0%E3%81%91%E3%81%A7%E3%81%AA%E3%81%8F%E3%80%810%E3%81%AB%E3%81%AA%E3%82%89%E3%81%AA%E3%81%8B%E3%81%A3%E3%81%9F%E3%82%BB%E3%83%AB%E3%81%AE%E6%95%B0%E3%82%92%E5%A4%A7%E3%81%8D%E3%81%8F%E3%81%99%E3%82%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf

In [19]:
inputs = np.zeros((4, 4))
inputs[:,0] = 128
inputs[:,2] = 128
print(inputs)

layer = tf.keras.layers.Dropout(0.4)

outputs = layer(inputs.reshape((-1, 4, 4)), training=True)
outputs = outputs.numpy().reshape((4, 4))
print(outputs)

[[128.   0. 128.   0.]
 [128.   0. 128.   0.]
 [128.   0. 128.   0.]
 [128.   0. 128.   0.]]
[[213.33333   0.        0.        0.     ]
 [213.33333   0.      213.33333   0.     ]
 [213.33333   0.      213.33333   0.     ]
 [  0.        0.        0.        0.     ]]


In [15]:
128 / (1 - 0.4)

213.33333333333334

In [20]:
layer = tf.keras.layers.Dropout(1.0)
layer(inputs.reshape((-1, 4, 4)), training=True)

ValueError: ignored

https://keras.io/api/layers/regularization_layers/dropout/  
0にならない入力は、1/(1 - rate)でスケールアップされ、全入力の合計が変化しないようにする。