<a href="https://colab.research.google.com/github/penguinshunya/ml/blob/main/%E6%B7%B1%E3%81%84%E5%B1%A4%E3%81%AF%E5%A4%A7%E3%81%8D%E3%81%84%E5%80%A4%E3%82%92%E5%87%BA%E5%8A%9B%E3%81%99%E3%82%8B%E3%81%8B%EF%BC%9F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [7]:
inputs = tf.keras.layers.Input((1,))
outputs = tf.keras.layers.Dense(1)(inputs)
model = tf.keras.Model(inputs, outputs)
model(np.ones((1, 1)))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.9002898]], dtype=float32)>

In [6]:
inputs = tf.keras.layers.Input((1,))
x = inputs
for i in range(100):
  x = tf.keras.layers.Dense(1)(x)
outputs = x
model = tf.keras.Model(inputs, outputs)
model(np.ones((1, 1)))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-6.409588e-22]], dtype=float32)>

In [8]:
inputs = tf.keras.layers.Input((3, 3, 3))
outputs = tf.keras.layers.Conv2D(3, 3, padding="same")(inputs)
model = tf.keras.Model(inputs, outputs)
model(np.ones((1, 3, 3, 3)))

<tf.Tensor: shape=(1, 3, 3, 3), dtype=float32, numpy=
array([[[[-0.5177243 ,  0.27364734, -0.54069674],
         [-1.27762   ,  0.3109943 , -1.3589487 ],
         [-0.87121797,  0.26136184, -0.85414433]],

        [[-0.7079085 ,  0.2595376 , -0.4479664 ],
         [-1.5389167 ,  0.3572798 , -1.8204361 ],
         [-1.0643494 ,  0.25396073, -1.2536467 ]],

        [[-0.43340284,  0.5078733 , -0.22711307],
         [-1.1337273 ,  0.51642233, -1.0700166 ],
         [-0.6426104 ,  0.39533648, -0.69759786]]]], dtype=float32)>

In [9]:
inputs = tf.keras.layers.Input((3, 3, 3))
x = inputs
for i in range(100):
  x = tf.keras.layers.Conv2D(3, 3, padding="same")(x)
outputs = x
model = tf.keras.Model(inputs, outputs)
model(np.ones((1, 3, 3, 3)))

<tf.Tensor: shape=(1, 3, 3, 3), dtype=float32, numpy=
array([[[[ 8.3368635e-14,  2.2209116e-12,  1.8648605e-12],
         [-4.1239052e-12, -1.5477795e-12, -1.2504631e-12],
         [-8.2127838e-12, -3.3113369e-12,  4.2099414e-12]],

        [[ 1.6233559e-13,  2.2665084e-12, -4.3576709e-12],
         [-7.7985561e-12, -2.8837826e-14, -1.2265347e-11],
         [-7.2633687e-12, -1.7134482e-13, -1.2743486e-12]],

        [[ 1.2094982e-12,  1.9076130e-12, -7.2865863e-12],
         [ 6.8356562e-13,  3.9845037e-13, -3.4530371e-12],
         [-4.1675665e-12, -4.3725305e-12,  1.6145129e-12]]]],
      dtype=float32)>

層が深くなるほど値は小さくなる